# Generated by Django 3.0.5 on 2020-04-27 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import summarize.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SplitPath', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideoPath', models.FileField(null=True, upload_to=summarize.models.user_directory_path, validators=[summarize.models.file_size], verbose_name='')),
                ('Name', models.CharField(max_length=400)),
                ('UserID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SplitSpeech',
            fields=[
                ('SplitID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summarize.Split')),
                ('SpeechPath', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SplitTranscript',
            fields=[
                ('SplitID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summarize.Split')),
                ('Transcript', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SplitTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.TextField()),
                ('SplitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarize.Split')),
            ],
        ),
        migrations.CreateModel(
            name='SplitSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary', models.TextField()),
                ('SplitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarize.Split')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('email', models.EmailField(default='', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SplitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarize.Split')),
                ('VideoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarize.Video')),
            ],
            options={
                'unique_together': {('VideoID', 'SplitID')},
            },
        ),
    ]
